name: flutter_sdl_gamepad
description: A Flutter wrapper around package:sdl_gamepad
version: 1.1.0
repository: https://github.com/BinghamtonRover/flutter_sdl_gamepad

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  sdl_gamepad: ^1.1.1
  sdl3: ^0.1.44

dev_dependencies:
  very_good_analysis: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
        dartPluginClass: FlutterSdlGamepad
      windows:
        ffiPlugin: true
        dartPluginClass: FlutterSdlGamepad
      macos:
        ffiPlugin: true
        pluginClass: FlutterSdlGamepadPlugin
        dartPluginClass: FlutterSdlGamepad
